name: "Dependency Review"
on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

permissions: read-all|write-all

jobs:
  dependency-review:
    uses: marvinIsSacul/kg-test-workflow/.github/workflows/ci-dependency-review.yml@main
